### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005) with Windows 10 and JDK 11

### ISSUE THREAD

**Issue by mondain** [corretto/corretto-11#178]
While this issue is not specific to Corretto 11, it is a bug in the JDK 11 core. A bug has been submitted to Oracle and no response or action has occurred within the last month (Feb 2021). I am repeating the content here in hopes of some sort of resolution as the Corretto team has been far more responsive to issues thus far.

### Describe the bug
On Windows 10 with Corretto 11, running a java application built with JNI calls, a rather simple array allocation causes a crash. On Ubuntu 18 with Corretto 11, the exact same application runs as expected.

### To Reproduce
A project here with all the code and instructions is here: https://github.com/mondain/buggy/tree/main/jdk11win10

### Expected behavior
The application should run without crashing the JVM.

### Platform information
    OS: Windows 10
    Version 

```
openjdk version "11.0.10" 2021-01-19 LTS
OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)
```

**Comment by davecurrie** [comment]
Thanks for getting in touch. We're taking a look and will get back once we've had a chance to try and reproduce the problem.

**Comment by navyxliu** [comment]
hi, @mondain, 

I read your logs on Windows. 

```
Failed output on Windows 10:

Opening main
Main new: 2675066083424
Main open
JMain opened: 2675066083424
Opened main for id: 2675066083424; now attempting close
JMain close: 2675066083424
Main remove: -698541984
Main close
```
`Main remove: -698541984` draw my attention. I found [your code](https://github.com/mondain/buggy/blob/main/jdk11win10/main.cpp#L85) converts id's types jlong -> long -> uintptr_t.
 
I don't think it's 100% safe because long is 4  bytes on Windows according to the following documents: 
https://docs.microsoft.com/en-us/cpp/cpp/data-type-ranges?view=msvc-160
https://en.wikipedia.org/wiki/64-bit_computing#64-bit_data_models

I guess when your code does conversation from jlong to long,  you got data lost silently on Windows. 
On the other side, sizeof(long) is 8 bytes on Linux with LP64.

**Comment by mondain** [comment]
@navyxliu While I don't imply that there are no unsafe operations, know that the code works fine as-is in Ubuntu with JDK 11 and JDK 8; in addition it also works fine Windows 10 with JDK 8. The problem is with JDK 11 on Windows; the code is a simple example to demonstrate the JVM crash.

**Comment by navyxliu** [comment]
Could you compile main.cpp using /W3?

```
with /W3 you get the error:
 c:\wsjdk\buggy\jdk11win10>cl /I "%JAVA_HOME%\include" /I "%JAVA_HOME%\include\win32" main.cpp /LD /W3
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27043 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
main.cpp
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xlocale(319): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
main.cpp(85): warning C4244: 'argument': conversion from 'jlong' to 'long', possible loss of data
```
From what I got, the conversation from jlong to long is unsafe. There is a risk to lose data for this conversation. We should not ignore the warning here. 

It's unsafe because it depends on your runtime value.  If `id` is a small integer, which can be presented within 32bits, then you are perfectly fine.  If there are bits on the higher 32bits, then (long)id will lose data and (uintptr_t)(long)id will yield a wrong pointer.
I guess that's the reason your program crashed on Windows 10.

**Comment by mondain** [comment]
@navyxliu Thanks for the info, but the unsafe operation is not the issue nor the reason for the JVM crash.

**Comment by mondain** [comment]
@navyxliu Keep in mind that I am also not an expert in C++ or JNI, but I know enough. If the type conversion is the problem crashing the JVM, then why? Also in addition, why is only crashing in Windows when running JDK 11; the other scenarios work as expected without any crash.

**Comment by eastig** [comment]
Hi @mondain,
@navyxliu is right. The crash is caused by conversion: `jlong->long`.
As C++ `jlong` represents Java `long`, `sizeof(jlong) == 8`. For C++ `long`, `sizeof(long) == 4` on 64-bit Windows. On 64-bit Windows the size of a pointer in 64-bit applications is 8 bytes. This is important because you use:
```
OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)
```
Now let's analyze your log:
```
1: Opening main
2: Main new: 2675066083424
3: Main open
4: JMain opened: 2675066083424
5: Opened main for id: 2675066083424; now attempting close
6: JMain close: 2675066083424
7: Main remove: -698541984
8: Main close
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffa3cef1360, pid=11012, tid=5204
```
According to line 1, you've got a pointer `Main *` with value `2675066083424`. The hex value of it is `0x0000026ed65d1860`. You can see it is 8 bytes and the higher 4 bytes are not zeros.
So you have returned the pointer to the Java code and got it back from the Java code unchanged, line 6. Then you called `main_ctx.RemoveMain(id)`.
```
long MainContext::RemoveMain(long id)
{
	std::cout << "Main remove: " << id << std::endl;
    uintptr_t locate = (uintptr_t) id;
    Main *m = (Main *) locate;
    if (m != 0) {
        m->close();
        delete m;
    } else {
        std::cerr << "Main not found at remove" << std::endl;
    }
    return 0;
}
```
As the function parameter `id` is `long` which size is 4 bytes. It cannot hold 8 byte value `0x0000026ed65d1860`. So only 4 bytes of it are used. The value is implicitly converted to `long`.
According to line 7, the value `RemoveMain` got was `-698541984`. The hex value of it is `0xd65d1860`. You can see this is the lower 4 bytes of `0x0000026ed65d1860`. So converting the value to a pointer created an invalid pointer. It is not zero. So `m->close()` was executed.
Now let me explain why the program printed out line 8.
In C++ member functions have a hidden parameter `this` which is a pointer to the instance of a class. So `m->close()` means a call of a member function `Main::close()` with `this == 0x00000000d65d1860`. BTW, calling a member function with an invalid instance pointer is undefined behaviour in C++. At the time of the call the pointer was not accessed. So the first line of `Main::close` was executed:
```
std::cout << "Main close" << std::endl;
```
It produced line 8. Then `free(data);` was executed. `free(data)` actually means `free(this->data)`.  This is where the invalid pointer was accessed. This caused access violation. It does not crash JVM immediately because JVM installs exception handlers. See https://docs.oracle.com/en/java/javase/11/troubleshoot/handle-signals-and-exceptions.html#GUID-CBA7BA16-F89F-4BE2-B653-139BABA997D4 for details. The purpose of the handler is to collect enough information about JVM state to help to debug the crash. The text after line 8 is what the exception handler had generated before JVM exited.

Your program will only work when the size of a pointer equals to the size of `long` or when the higher 4 bytes of a pointer are zeros.
The size of a pointer equals to the size of `long`:
- On Linux, in both 32-bit and 64-bit applications.
- On Windows, in 32-bit applications.

This explains why you don't see crashes on Linux. Regarding JDK8, I think you either using 32-bit version or get lucky to have zeros in the higher 4 bytes. You can check this with `java -version` and with pointer values in output logs.

Hope this helps.

Kind regards,
Evgeny Astigeevich

**Comment by mondain** [comment]
@eastig @navyxliu I will make the change to the example to prevent the conversion and re-test; I want to thank you for helping to sort this out so quickly and with great details. :)

**Comment by mondain** [comment]
Closing this issue since avoiding the conversion to `long` has resolved the crash on Windows; thanks to all who helped.
