### ISSUE TITLE
Corretto-11 JRE download?

### ISSUE THREAD

**Issue by mrelmattador** [corretto/corretto-11#58]
Are there plans to produce a 11 JRE?  I can find it for corretto-8, but looks like there hasn't been one created for 11, only JDK builds.

**Comment by navyxliu** [comment]
No, we don't have a plan to release JRE11. 

Java11 features the module system and module linker, so you can't carry over the experiences like JDK/JRE to JDK9+.  There's no JRE11 per se. Actually, you can use jlink to generate the 'minimal JRE' for you application!  That's why we are reluctant to have a 'JRE11'.  What we release must be a super fat one because we can't make any assumption for customer's application.

A good practice for java11 with docker is to generate JRE in dockerfile.
