### ISSUE TITLE
Inconsistent zip packaging across OS downloads

### ISSUE THREAD

**Issue by amir-khassaia** [corretto/corretto-11#61]
### Describe the bug
The download zips of the JDK distributions on https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html are inconsistent with each other across operating systems in terms of the top folder name in each one.
Eg. Windows zip expands to jdk11.0.5_10, while linux and mac use amazon-corretto-11.0.5.10-linux-x64 and amazon-coretto-11.jdk as their folder respectively.
While this is a minor cosmetic issue it would be nice to have a consistent structure such that any scripts that use these don't have to be aware of these inconsistencies.

### To Reproduce
Steps and (source) code to reproduce the behavior.
Download each zip and look at top folder

### Screenshots
![image](https://user-images.githubusercontent.com/4484681/69673621-d03ad980-10ee-11ea-85d1-53a982afba83.png)

### Platform information
    OS: All
    Version 11.0.5

**Comment by alvdavi** [comment]
Thanks for the message, we will take it into consideration.

However, this inconsistency is intentional, as each zip/tgz mirrors the folder name that is installed on the respective OS (msi, pkg or rpm). And this can go further than just change the name of the folder, for example, in the Mac version the actual JDK is located under `amazon-corrett-11.jdk/Contents/Home`.
